/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import DBALEX.*;

/**
 *
 * @author mac
 */
public class FRMSELECHABI extends javax.swing.JFrame {

     private Conexion bd = new Conexion();
     FRMRESERVA resv;
     
     public /*static*/ String respuesta;
    /**
     * Creates new form FRMSELECHABI
     */
    public FRMSELECHABI() {
        initComponents();
        this.ListarDatos();
    }
    
    public FRMSELECHABI(FRMRESERVA reser){
        resv= reser;
        initComponents();
        this.ListarDatos();
    }
    
    public void ListarDatos(){
        bd.MostrarHabitacionDispo(tblhabitaciones);
    }
    
    public void BuscaDatos(String buscar){
        bd.identificar_bsqueda(tblhabitaciones,buscar,"Habitacion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TXTBUSCAR = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhabitaciones = new javax.swing.JTable();
        BTNSELEC = new javax.swing.JButton();
        BTNBuscar = new javax.swing.JButton();
        BTNMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("BUSCAR POR ID HABITACION:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(TXTBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 15, 110, 30));

        tblhabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Num. Habitacion", "Tipo Habitacion", "Numero Camas", "Capacidad", "Estado", "Precio", "Extra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblhabitaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 470, 180));

        BTNSELEC.setText("Seleccionar");
        BTNSELEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSELECActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSELEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 150, 40));

        BTNBuscar.setText("Buscar");
        BTNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(BTNBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        BTNMostrar.setText("Mostrar Todo");
        BTNMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(BTNMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void BTNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarActionPerformed
        BuscaDatos(this.TXTBUSCAR.getText());
    }//GEN-LAST:event_BTNBuscarActionPerformed

    private void BTNMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMostrarActionPerformed
                this.ListarDatos();
    }//GEN-LAST:event_BTNMostrarActionPerformed

    private void BTNSELECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSELECActionPerformed
        respuesta= bd.seleccionarhabi(tblhabitaciones);
        if(resv.isShowing()){
            resv.LBLCODIGOHABI.setText(respuesta);
            this.setVisible(false);
        }
        else{
            System.out.println("ERROR ALEX-100: NO hay una ventana abierta para recibir el dato");
        }
    }//GEN-LAST:event_BTNSELECActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMSELECHABI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMSELECHABI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMSELECHABI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMSELECHABI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMSELECHABI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscar;
    private javax.swing.JButton BTNMostrar;
    private javax.swing.JButton BTNSELEC;
    private javax.swing.JTextField TXTBUSCAR;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblhabitaciones;
    // End of variables declaration//GEN-END:variables
}
